cloud_provider: null
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: nats
    release: bosh
  - name: postgres-9.4
    release: bosh
  - name: blobstore
    release: bosh
  - name: director
    release: bosh
  - name: health_monitor
    release: bosh
  - name: vsphere_cpi
    release: bosh-vsphere-cpi
  name: bosh
  networks:
  - name: dev-infra
    static_ips:
    - 10.213.13.6
  persistent_disk_type: bosh
  properties:
    agent:
      mbus: nats://natsuser:REDACTED@10.213.13.6:4222
    blobstore:
      address: 10.213.13.6
      agent:
        password: REDACTED
        user: blobstore-user
      director:
        password: REDACTED
        user: director-user
      port: 25250
      provider: dav
    director:
      address: 10.213.13.6
      cpi_job: vsphere_cpi
      db:
        adapter: postgres
        database: bosh
        host: 127.0.0.1
        listen_address: 127.0.0.1
        password: REDACTED
        user: boshdb
      enable_dedicated_status_worker: true
      enable_nats_delivered_templates: true
      enable_post_deploy: true
      events:
        record_events: true
      flush_arp: true
      generate_vm_passwords: true
      name: drgao-bill-vsphere-sandbox-bosh-genesis-kit
      ssl:
        cert: REDACTED
        key: REDACTED
      user_management:
        local:
          users:
          - name: resurrector
            password: REDACTED
          - name: admin
            password: REDACTED
        provider: local
      workers: 4
    hm:
      director_account:
        ca_cert: REDACTED
        password: REDACTED
        user: resurrector
      resurrector_enabled: true
    nats:
      address: 127.0.0.1
      password: REDACTED
      user: natsuser
    ntp:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    postgres:
      adapter: postgres
      database: bosh
      host: 127.0.0.1
      listen_address: 127.0.0.1
      password: REDACTED
      user: boshdb
    vcenter:
      address: REDACTED
      datacenters:
      - clusters:
        - cluster1
        datastore_pattern: ^(vol309|vol310)$
        disk_path: drgao-bill-vsphere-sandbox/disks
        name: Interxion MAD2
        persistent_datastore_pattern: ^(vol309|vol310)$
        template_folder: drgao-bill-vsphere-sandbox/templates
        vm_folder: drgao-bill-vsphere-sandbox/vms
      password: REDACTED
      user: REDACTED
  stemcell: default
  vm_type: small
name: drgao-bill-vsphere-sandbox-bosh-genesis-kit
releases:
- name: bosh
  sha1: 37630c636a030454d55703cfdd495d733525353f
  url: https://s3.amazonaws.com/bosh-compiled-release-tarballs/bosh-263.2.0-ubuntu-trusty-3445.7-20170915-052445-759948783-20170915052451.tgz?versionId=3kjVQuRK7JyrnbKEbKhLRi7qyo0wBXZJ
  version: 263.2.0
- name: bosh-vsphere-cpi
  sha1: b5f3c53c800d6c8a9182b263ec239a952f33ba67
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release?v=45
  version: 45
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
update:
  canaries: 1
  canary_watch_time: 30000-120000
  max_in_flight: 1
  serial: true
  update_watch_time: 30000-120000
variables: []

