cloud_provider:
  certificate: REDACTED
  mbus: https://mbus:REDACTED@10.213.13.5:6868
  properties:
    agent:
      mbus: https://mbus:REDACTED@10.213.13.5:6868
    blobstore:
      path: /var/vcap/micro_bosh/data/cache
      provider: local
    ntp:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    vcenter:
      address: REDACTED
      datacenters:
      - clusters:
        - cluster1
        datastore_pattern: ^(vol309|vol310)$
        disk_path: drgao-bill-vpshere-proto-bosh/disks
        name: Interxion MAD2
        persistent_datastore_pattern: ^(vol309|vol310)$
        template_folder: drgao-bill-vpshere-proto-bosh/templates
        vm_folder: drgao-bill-vpshere-proto-bosh/vms
      password: REDACTED
      user: REDACTED
  template:
    name: vsphere_cpi
    release: bosh-vsphere-cpi
disk_pools:
- cloud_properties:
    type: preallocated
  disk_size: 32768
  name: bosh
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: nats
    release: bosh
  - name: postgres-9.4
    release: bosh
  - name: blobstore
    release: bosh
  - name: director
    release: bosh
  - name: health_monitor
    release: bosh
  - name: vsphere_cpi
    release: bosh-vsphere-cpi
  name: bosh
  networks:
  - name: bosh
    static_ips:
    - 10.213.13.5
  persistent_disk_pool: bosh
  properties:
    agent:
      mbus: nats://natsuser:REDACTED@10.213.13.5:4222
    blobstore:
      address: 10.213.13.5
      agent:
        password: REDACTED
        user: blobstore-user
      director:
        password: REDACTED
        user: director-user
      port: 25250
      provider: dav
    director:
      address: 10.213.13.5
      cpi_job: vsphere_cpi
      db:
        adapter: postgres
        database: bosh
        host: 127.0.0.1
        listen_address: 127.0.0.1
        password: REDACTED
        user: boshdb
      enable_dedicated_status_worker: true
      enable_nats_delivered_templates: true
      enable_post_deploy: true
      events:
        record_events: true
      flush_arp: true
      generate_vm_passwords: true
      name: drgao-bill-vpshere-proto-bosh-bosh-genesis-kit
      ssl:
        cert: REDACTED
        key: REDACTED
      user_management:
        local:
          users:
          - name: resurrector
            password: REDACTED
          - name: admin
            password: REDACTED
        provider: local
      workers: 4
    hm:
      director_account:
        ca_cert: REDACTED
        password: REDACTED
        user: resurrector
      resurrector_enabled: true
    nats:
      address: 127.0.0.1
      password: REDACTED
      user: natsuser
    ntp:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    postgres:
      adapter: postgres
      database: bosh
      host: 127.0.0.1
      listen_address: 127.0.0.1
      password: REDACTED
      user: boshdb
    vcenter:
      address: REDACTED
      datacenters:
      - clusters:
        - cluster1
        datastore_pattern: ^(vol309|vol310)$
        disk_path: drgao-bill-vpshere-proto-bosh/disks
        name: Interxion MAD2
        persistent_datastore_pattern: ^(vol309|vol310)$
        template_folder: drgao-bill-vpshere-proto-bosh/templates
        vm_folder: drgao-bill-vpshere-proto-bosh/vms
      password: REDACTED
      user: REDACTED
  resource_pool: small
  stemcell: default
name: drgao-bill-vpshere-proto-bosh-bosh-genesis-kit
networks:
- name: bosh
  subnets:
  - cloud_properties:
      name: net-10-213-0-0
    dns:
    - 10.58.111.31
    gateway: 10.213.0.1
    range: 10.213.0.0/20
    static:
    - 10.213.13.5
  type: manual
releases:
- name: bosh
  sha1: 37630c636a030454d55703cfdd495d733525353f
  url: https://s3.amazonaws.com/bosh-compiled-release-tarballs/bosh-263.2.0-ubuntu-trusty-3445.7-20170915-052445-759948783-20170915052451.tgz?versionId=3kjVQuRK7JyrnbKEbKhLRi7qyo0wBXZJ
  version: 263.2.0
- name: bosh-vsphere-cpi
  sha1: b5f3c53c800d6c8a9182b263ec239a952f33ba67
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release?v=45
  version: 45
resource_pools:
- cloud_properties:
    cpu: 2
    disk: 40960
    ram: 4096
  env:
    bosh:
      password: REDACTED
  name: small
  network: bosh
  stemcell:
    sha1: d89d0f08d748a8a07d05dca915cd9ddfcdee52a6
    url: https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-trusty-go_agent?v=3468.1
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
update:
  canaries: 1
  canary_watch_time: 30000-120000
  max_in_flight: 1
  serial: true
  update_watch_time: 30000-120000
variables: null

